name: Fly Deploy (Frontend)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group # Đảm bảo chỉ có 1 job deploy chạy tại một thời điểm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
